[build]
  command = ""
  publish = "/"
  [[redirects]]
  from = "http://www.willgreen.net/*"
  to = "https://copyroad.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://www.willgreen.net/*"
  to = "https://copyroad.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "http://willgreen.net/* "
  to = "https://copyroad.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://willgreen.net/* "
  to = "https://copyroad.com/:splat"
  status = 301
  force = true

